---

- hosts: webservers
  name: create a directory
  become: yes
  become_user: root


  tasks: 
   
     - name: create a folder dir
       file:
          path: "/tmp/{{ dir }}"
          state: directory
          recurse: yes
          mode: "0700"
          owner: root
          group: root
       tags:
         - file


     - name: copy file 
       copy: 
         src: HR-file 
         dest: "/tmp/{{ dir }}"
         group: root
         owner: root 
         mode: 0600
       tags: 
         - file
