---

- name: install httpd server
  hosts: [webservers]
  become: yes 
  become_user: root 
  
  tasks: 

     - name: installing httpd 
       yum: 
         name: httpd 
         state: present  
  
     
     - name: installing htop 
       yum: 
       name: htop 
       state: present
  tags: htop        

